import { Layout } from "@/components/layout/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ApolloProvider } from "@apollo/client";
import gqlClient from "@/lib/gql_client";
import { GqlProvider } from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <div className="flex">
          <div className="flex flex-col bg-blue-950 w-40 h-screen">
            <span className="text-lg h-10 font-thin">マイページ</span>
            <Link href="/" className="text-lg font-bold h-10">
              Home
            </Link>
            <Link href="/timecard" className="text-lg font-bold h-10">
              打刻
            </Link>
            <Link href="/attendance" className="text-lg font-bold h-10">
              出勤簿
            </Link>
          </div>
          {/* <div className="w-full">{children}</div> */}
          <GqlProvider>
            <div className="w-full">{children}</div>
          </GqlProvider>
        </div>
      </body>
    </html>
  );
}
