// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	CreatedAt string `json:"createdAt"`
	UserID    string `json:"userId"`
}

type Mutation struct {
}

type NewMessage struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	DeletedAt string `json:"deletedAt"`
}
