version: "3"
services:
  sysctl:
    image: alpine
    container_name: sysctl
    command: ["sysctl", "-w", "vm.max_map_count=262144"]
    privileged: true
    networks:
      - esnet
  es01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es01
    environment:
      - node.name=es01
      # - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    depends_on:
      - sysctl

volumes:
  esdata01:
    driver: local

networks:
  esnet:
